name: Run Tests and Archive Code Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2  # Use actions/checkout@v3 if you prefer
      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Use actions/setup-java@v3 if you prefer
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Run all tests in project
        run: |
          mvn compile
          mvn test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2  # Use actions/upload-artifact@v3 if you prefer
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: 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
      - name: Build and publish updated image
        run: |
            mvn package
            docker build . --tag ghcr.io/casillas0905/via-tabloid:latest
            docker push ghcr.io/casillas0905/via-tabloid:latest

