apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-doc-example
  template:
    metadata:
      labels:
        app: k8s-doc-example
    spec:
      containers:
        - name: k8s-doc-example
          image: k8s-doc-example:v1.25.9
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
